/* eslint-disable import/no-anonymous-default-export */
import { getRole } from './cookie';

export const items = {
  BUSINESS_PERFORMANCE: 'business_performance',
  CUSTOMER_JOURNEY: 'customer_journey',
  DETAIL_ACTIVE_USER: 'detail_active_user',
  DETAIL_ACTIVE_USER_TREG: 'detail_active_user_treg',
  DETAIL_ACTIVE_USER_WITEL: 'detail_active_user_witel',
  NETMONK: 'netmonk',
  NETMONK_FULFILLMENT: 'netmonk_fulfillment',
  NETMONK_HI: 'netmonk_hi',
  NETMONK_PRIME: 'netmonk_prime',
  MONITORING_APPLICATION: 'monitoring_aplication',
  MONITORING_CUSTOMER: 'monitoring_customer',
  MONITORING_DEVICE_PELANGGAN: 'monitoring_device_pelanggan',
  MONITORING_DIGITAL_CUSTOMER: 'monitoring_digital_customer',
  MONITORING_FULFILLMENT: 'monitoring_fulfillment',
  MONITORING_ORDER_SCONE: 'monitoring_order_scone',
  MONITORING_WEBSITE: 'monitoring_website',
  ORDER_NCX: 'order_ncx',
  ORDER_NCX_DBS: 'order_ncx_dbs',
  ORDER_NCX_INTERNAL: 'order_ncx_internal',
  ORDER_NCX_TREG: 'order_ncx_treg',
  ORDER_NCX_WITEL: 'order_ncx_witel',
  ORDER_ON_PROGRESS: 'order_on_progress',
  ORDER_SCONE: 'order_scone',
  ORDER_SCONE_TREG: 'order_scone_treg',
  ORDER_SCONE_WITEL: 'order_scone_witel',
  ORDER_SCONE_V2: 'order_scone_v2',
  ORDER_WFM: 'order_wfm',
  OVERVIEW: 'overview',
  REPORT_LATENCY: 'report_latency',
  REPORT_PACKET_LOSS: 'report_packet_loss',
  REPORT_JITTER: 'report_jitter',
  USER_NETMONK_HI: 'user_netmonk_hi',
  USER_OVERVIEW: 'user_overview',
};

export const acc = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
};

const rules = [
  {
    role: 'business',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [acc.READ] },
      { name: items.CUSTOMER_JOURNEY, permission: [acc.READ] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [acc.READ] },
      { name: items.MONITORING_APPLICATION, permission: [acc.READ] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [acc.READ] },
      { name: items.MONITORING_FULFILLMENT, permission: [acc.READ] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [acc.READ] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [acc.READ] },
      { name: items.ORDER_NCX_INTERNAL, permission: [acc.READ] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'doa-dbt',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [acc.READ] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [acc.READ] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'fulfillment',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [acc.READ] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [acc.READ] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [acc.READ] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      {
        name: items.MONITORING_ORDER_SCONE,
        permission: [acc.READ, acc.UPDATE],
      },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [acc.READ] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [acc.READ] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [acc.READ, acc.UPDATE] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [acc.READ] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'netmonk',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [acc.READ] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [acc.READ] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [acc.READ] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'marketing',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [acc.READ] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [acc.READ] },
      { name: items.NETMONK_FULFILLMENT, permission: [] },
      { name: items.NETMONK_HI, permission: [] },
      { name: items.NETMONK_PRIME, permission: [acc.READ] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [acc.READ] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [acc.READ] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [acc.READ] },
      { name: items.ORDER_NCX_INTERNAL, permission: [acc.READ] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'product-owner',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [acc.READ] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [acc.READ] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [acc.READ] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [acc.READ] },
    ],
  },
  {
    role: 'qos',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      {
        name: items.DETAIL_ACTIVE_USER_TREG,
        permission: [],
      },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [acc.READ] },
      { name: items.NETMONK_FULFILLMENT, permission: [] },
      { name: items.NETMONK_HI, permission: [] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [acc.READ] },
      { name: items.REPORT_PACKET_LOSS, permission: [acc.READ] },
      { name: items.REPORT_JITTER, permission: [acc.READ] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'treg',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      {
        name: items.DETAIL_ACTIVE_USER_TREG,
        permission: [acc.READ, acc.UPDATE],
      },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [acc.READ] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [acc.READ] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    // role treg
    role: 'user',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      {
        name: items.DETAIL_ACTIVE_USER_TREG,
        permission: [acc.READ, acc.UPDATE],
      },
      { name: items.DETAIL_ACTIVE_USER_WITEL, permission: [] },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [acc.READ] },
      { name: items.ORDER_NCX_WITEL, permission: [] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [acc.READ] },
      { name: items.ORDER_SCONE_WITEL, permission: [] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
  {
    role: 'witel',
    access: [
      { name: items.BUSINESS_PERFORMANCE, permission: [] },
      { name: items.CUSTOMER_JOURNEY, permission: [] },
      { name: items.DETAIL_ACTIVE_USER, permission: [] },
      { name: items.DETAIL_ACTIVE_USER_TREG, permission: [] },
      {
        name: items.DETAIL_ACTIVE_USER_WITEL,
        permission: [acc.READ, acc.UPDATE],
      },
      { name: items.NETMONK, permission: [] },
      { name: items.NETMONK_FULFILLMENT, permission: [acc.READ] },
      { name: items.NETMONK_HI, permission: [acc.READ] },
      { name: items.NETMONK_PRIME, permission: [] },
      { name: items.MONITORING_APPLICATION, permission: [] },
      { name: items.MONITORING_CUSTOMER, permission: [] },
      { name: items.MONITORING_DEVICE_PELANGGAN, permission: [] },
      { name: items.MONITORING_DIGITAL_CUSTOMER, permission: [] },
      { name: items.MONITORING_FULFILLMENT, permission: [] },
      { name: items.MONITORING_ORDER_SCONE, permission: [] },
      { name: items.MONITORING_WEBSITE, permission: [] },
      { name: items.ORDER_NCX, permission: [] },
      { name: items.ORDER_NCX_DBS, permission: [] },
      { name: items.ORDER_NCX_INTERNAL, permission: [] },
      { name: items.ORDER_NCX_TREG, permission: [] },
      { name: items.ORDER_NCX_WITEL, permission: [acc.READ] },
      { name: items.ORDER_ON_PROGRESS, permission: [] },
      { name: items.ORDER_SCONE, permission: [] },
      { name: items.ORDER_SCONE_TREG, permission: [] },
      { name: items.ORDER_SCONE_WITEL, permission: [acc.READ] },
      { name: items.ORDER_SCONE_V2, permission: [] },
      { name: items.ORDER_WFM, permission: [] },
      { name: items.OVERVIEW, permission: [acc.READ] },
      { name: items.REPORT_LATENCY, permission: [] },
      { name: items.REPORT_PACKET_LOSS, permission: [] },
      { name: items.REPORT_JITTER, permission: [] },
      { name: items.USER_NETMONK_HI, permission: [] },
      { name: items.USER_OVERVIEW, permission: [] },
    ],
  },
];

export const hasAccess = (item, perm) => {
  const userRole = getRole();
  if (userRole === null) return false;
  const find = rules.filter((el) => el.role === userRole);
  if (find.length === 0) return false;
  const { access } = rules.filter((el) => el.role === userRole)[0];
  const permission = access.filter((el) => el.name === item)[0]?.permission;
  if (permission !== undefined) {
    if (permission.includes(perm)) return true;
  }
  return false;
};

export default {
  hasAccess,
};
